# -*- coding: utf-8 -*-
"""3_speach_to_text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EB-p4iHg2ycQhVcxs2z1GkwnHsJkqzES
"""

# Colab da birinchi run qiling:
!pip install -q transformers datasets librosa soundfile evaluate accelerate

# So'ng yuqoridagi kodni ishlating

# Colab da:
!pip install -q transformers datasets librosa soundfile evaluate accelerate

# Keyin kodni ishlating

# ============================================================
# 1-QADAM: kutubxonalarni o'rnatish va runtime'ni avtomatik qayta ishga tushirish
# Bu katakchani BIR MARTA ishga tushiring. Runtime o'zi qayta ishga tushadi
# ("Session crashed" deb yozadi — bu normal). Keyin shu katakchani YANA BIR
# MARTA ishga tushiring (endi flag fayl borligi sababli o'tib ketadi),
# so'ngra qolgan barcha katakchalarni ketma-ket davom ettiring.
# ============================================================
import os

FLAG_FILE = "/content/.deps_installed"

if not os.path.exists(FLAG_FILE):
    os.system(
        'pip install -q "datasets==2.21.0" transformers accelerate peft '
        'bitsandbytes librosa soundfile evaluate jiwer tensorboard huggingface_hub'
    )
    with open(FLAG_FILE, "w") as f:
        f.write("done")
    print("O'rnatish tugadi. Runtime avtomatik qayta ishga tushiriladi...")
    os.kill(os.getpid(), 9)
else:
    print("Paketlar allaqachon o'rnatilgan. Davom etishingiz mumkin.")

# ============================================================
# 2-QADAM: Hugging Face login
# Common Voice ba'zi versiyalari uchun token talab qilinadi
# https://huggingface.co/settings/tokens
# ============================================================
from huggingface_hub import notebook_login
notebook_login()


# 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

# ============================================================
# 3-QADAM: GPU tekshirish
# ============================================================
import torch
print('CUDA mavjud:', torch.cuda.is_available())
if torch.cuda.is_available():
    print('GPU:', torch.cuda.get_device_name(0))
    print('Xotira (GB):', round(torch.cuda.get_device_properties(0).total_memory / 1e9, 2))

# =====================================================
# 4-QADAM (7-QADAMDAN OLDIN BUNI ISHLATING)
# =====================================================

from datasets import load_dataset, DatasetDict

uz_data = DatasetDict()
uz_data["train"] = load_dataset("yakhyo/mozilla-common-voice-uzbek", split="train")
uz_data["test"] = load_dataset("yakhyo/mozilla-common-voice-uzbek", split="test")

print("✅ 4-qadam: Dataset yuklandi!")
print(f"📊 Train: {len(uz_data['train'])}, Test: {len(uz_data['test'])}")

# ============================================================
# 4-QADAM: DATASET YUKLASH (TO'G'RI)
# ============================================================

from datasets import load_dataset, DatasetDict, Audio

print("🔄 Dataset yuklanmoqda...")

# ⭐ Dataset yuklash
uz_data = DatasetDict()
uz_data["train"] = load_dataset(
    "yakhyo/mozilla-common-voice-uzbek",
    split="train"
)

# ⭐ Test ni train dan ajratamiz
split = uz_data["train"].train_test_split(test_size=0.1, seed=42)
uz_data["train"] = split["train"]
uz_data["test"] = split["test"]

# ⭐ Audio ni 16000 Hz ga o'tkazish
uz_data = uz_data.cast_column("audio", Audio(sampling_rate=16000))

print(f"✅ Train: {len(uz_data['train'])}, Test: {len(uz_data['test'])}")

# ⭐ Tekshirish
print("\n📊 Dataset columnlari:")
print(uz_data["train"].column_names)

print("\n📊 Birinchi element kalitlari:")
print(uz_data["train"][0].keys())

print("\n📊 Audio mavjudligi:")
print("audio" in uz_data["train"][0])
print("sentence" in uz_data["train"][0])

# =====================================================
# 6-QADAM: model, tokenizer, feature extractor
# =====================================================

from transformers import WhisperFeatureExtractor, WhisperTokenizer, WhisperProcessor

MODEL_NAME = "openai/whisper-medium"

feature_extractor = WhisperFeatureExtractor.from_pretrained(MODEL_NAME)
tokenizer = WhisperTokenizer.from_pretrained(MODEL_NAME, language="Uzbek", task="transcribe")
processor = WhisperProcessor.from_pretrained(MODEL_NAME, language="Uzbek", task="transcribe")

print("✅ Processor yuklandi!")

# ⭐ DISKNI TOZALASH (Colab/Kaggle da)
import os
import shutil

def clean_disk():
    """Diskni tozalash"""
    # 1. Hugging Face cache
    cache_dir = "/root/.cache/huggingface"
    if os.path.exists(cache_dir):
        shutil.rmtree(cache_dir)
        print("✅ HuggingFace cache tozalandi")

    # 2. Torch cache
    torch_cache = "/root/.cache/torch"
    if os.path.exists(torch_cache):
        shutil.rmtree(torch_cache)
        print("✅ Torch cache tozalandi")

    # 3. Pip cache
    pip_cache = "/root/.cache/pip"
    if os.path.exists(pip_cache):
        shutil.rmtree(pip_cache)
        print("✅ Pip cache tozalandi")

    # 4. Kaggle temp
    temp_dir = "/root/.cache/kagglehub"
    if os.path.exists(temp_dir):
        shutil.rmtree(temp_dir)
        print("✅ Kaggle cache tozalandi")

# ⭐ Diskni tozalash
clean_disk()

# Bo'sh joyni tekshirish
import shutil
total, used, free = shutil.disk_usage("/")
print(f"💾 Bo'sh joy: {free // (2**30)} GB")

# # ============================================================
# # 7-QADAM DAN OLDIN: XOTIRANI TOZALASH
# # ============================================================

# import gc
# import torch  # ⭐ MUHIM: torch import qilish kerak!
# import shutil

# # Bo'sh joyni tekshirish
# total, used, free = shutil.disk_usage("/")
# print(f"💾 Bo'sh joy: {free // (2**30)} GB")

# # Xotirani tozalash
# gc.collect()
# if torch.cuda.is_available():
#     torch.cuda.empty_cache()
#     print("✅ GPU cache tozalandi!")
# print("✅ RAM tozalandi!")

import gc
import torch
import numpy as np
import librosa
from datasets import Dataset

def process_dataset_batch(dataset, max_samples=100, batch_size=50):
    """Datasetni qismlarga bo'lib qayta ishlash"""
    all_input_features = []
    all_labels = []

    actual_samples = min(max_samples, len(dataset))
    print(f"📊 Jami: {actual_samples} ta misol qayta ishlanadi")

    if actual_samples == 0:
        print("⚠️ Dataset bo'sh!")
        return Dataset.from_dict({"input_features": [], "labels": []})

    for start in range(0, actual_samples, batch_size):
        end = min(start + batch_size, actual_samples)
        print(f"📊 {start}-{end} misollar qayta ishlanmoqda...")

        for i in range(start, end):
            try:
                item = dataset[i]

                if 'audio' not in item:
                    print(f"⚠️ {i}-elementda 'audio' yo'q!")
                    continue

                audio = item["audio"]

                if isinstance(audio, dict):
                    audio_array = audio.get("array")
                    sampling_rate = audio.get("sampling_rate", 16000)
                else:
                    audio_array = audio
                    sampling_rate = 16000

                if sampling_rate != 16000:
                    audio_array = librosa.resample(audio_array, orig_sr=sampling_rate, target_sr=16000)
                    sampling_rate = 16000

                input_features = processor.feature_extractor(
                    audio_array,
                    sampling_rate=sampling_rate,
                    return_tensors="np"
                ).input_features[0]

                sentence = item.get("sentence", " ")
                if not sentence:
                    sentence = " "

                labels = processor.tokenizer(
                    sentence,
                    padding="max_length",
                    max_length=128,
                    truncation=True,
                    return_tensors="np"
                ).input_ids[0]

                all_input_features.append(input_features)
                all_labels.append(labels)

            except Exception as e:
                # ⭐ XATOLIKNI KO'RSATISH
                print(f"⚠️ {i}-elementda xato: {e}")
                continue

        gc.collect()
        if torch.cuda.is_available():
            torch.cuda.empty_cache()

    print(f"✅ {len(all_input_features)} ta misol qayta ishlandi!")

    if len(all_input_features) == 0:
        print("⚠️ Hech qanday ma'lumot qayta ishlanmadi!")
        return Dataset.from_dict({"input_features": [], "labels": []})

    # ⭐ NUMPY ARRAYGA AYLANTIRISH
    input_features_array = np.array(all_input_features, dtype=np.float32)
    labels_array = np.array(all_labels, dtype=np.int64)

    print(f"📊 input_features_array shape: {input_features_array.shape}")
    print(f"📊 labels_array shape: {labels_array.shape}")

    # ⭐ XATOSIZ USUL
    new_dataset = Dataset.from_dict({
        "input_features": [],
        "labels": []
    })

    for i in range(len(input_features_array)):
        new_dataset = new_dataset.add_item({
            "input_features": input_features_array[i].tolist(),
            "labels": labels_array[i].tolist()
        })

    def to_numpy(batch):
        return {
            "input_features": np.array(batch["input_features"], dtype=np.float32),
            "labels": np.array(batch["labels"], dtype=np.int64)
        }

    new_dataset = new_dataset.map(to_numpy, num_proc=1)

    print(f"📊 Dataset columnlari: {new_dataset.column_names}")

    first_item = new_dataset[0]
    if hasattr(first_item['input_features'], 'shape'):
        print(f"📊 input_features shape: {first_item['input_features'].shape}")
    if hasattr(first_item['labels'], 'shape'):
        print(f"📊 labels shape: {first_item['labels'].shape}")

    return new_dataset

# ============================================================
# 7-QADAMNI ISHLATISH (750 TA)
# ============================================================

print("\n🔄 Ma'lumotlar qayta ishlanmoqda...")

print("📊 Train qayta ishlanmoqda...")
train_dataset = process_dataset_batch(uz_data["train"], max_samples=750, batch_size=100)

print("📊 Test qayta ishlanmoqda...")
test_dataset = process_dataset_batch(uz_data["test"], max_samples=150, batch_size=50)

uz_data = {
    "train": train_dataset,
    "test": test_dataset
}

print(f"✅ Train hajmi: {len(uz_data['train'])}")
print(f"✅ Test hajmi: {len(uz_data['test'])}")

if len(uz_data['train']) > 0:
    first = uz_data['train'][0]
    if hasattr(first['input_features'], 'shape'):
        print(f"📊 input_features shape: {first['input_features'].shape}")
    if hasattr(first['labels'], 'shape'):
        print(f"📊 labels shape: {first['labels'].shape}")
else:
    print("⚠️ Dataset bo'sh!")

# ============================================================
# 8-QADAM: data collator (batch yig'uvchi)
# ============================================================
from dataclasses import dataclass
from typing import Any, Dict, List, Union
import torch

@dataclass
class DataCollatorSpeechSeq2SeqWithPadding:
    processor: Any

    def __call__(self, features: List[Dict[str, Union[List[int], torch.Tensor]]]) -> Dict[str, torch.Tensor]:
        input_features = [{"input_features": f["input_features"]} for f in features]
        batch = self.processor.feature_extractor.pad(input_features, return_tensors="pt")

        label_features = [{"input_ids": f["labels"]} for f in features]
        labels_batch = self.processor.tokenizer.pad(label_features, return_tensors="pt")
        labels = labels_batch["input_ids"].masked_fill(labels_batch.attention_mask.ne(1), -100)

        if (labels[:, 0] == self.processor.tokenizer.bos_token_id).all().cpu().item():
            labels = labels[:, 1:]

        batch["labels"] = labels
        return batch

data_collator = DataCollatorSpeechSeq2SeqWithPadding(processor=processor)

# ============================================================
# 9-QADAM: baholash metrikasi (WER)
# ============================================================
import evaluate
metric = evaluate.load("wer")

def compute_metrics(pred):
    pred_ids = pred.predictions
    label_ids = pred.label_ids
    label_ids[label_ids == -100] = tokenizer.pad_token_id

    pred_str = tokenizer.batch_decode(pred_ids, skip_special_tokens=True)
    label_str = tokenizer.batch_decode(label_ids, skip_special_tokens=True)

    wer = 100 * metric.compute(predictions=pred_str, references=label_str)
    return {"wer": wer}

# ============================================================
# 10-QADAM: modelni 8-bit'da yuklash (xotira tejash uchun)
# ============================================================

import torch
from transformers import WhisperForConditionalGeneration, BitsAndBytesConfig

# ⭐ MODEL_NAME ni aniqlash (agar oldin aniqlanmagan bo'lsa)
try:
    MODEL_NAME
except NameError:
    MODEL_NAME = "openai/whisper-medium"
    print(f"📊 MODEL_NAME aniqlanmadi, default: {MODEL_NAME}")

print(f"📊 Model: {MODEL_NAME}")

# ⭐ 1. 8-bit konfiguratsiyasi
bnb_config = BitsAndBytesConfig(
    load_in_8bit=True,
    bnb_8bit_use_double_quant=True,
    bnb_8bit_quant_type="nf8",
)

# ⭐ 2. Modelni 8-bit'da yuklash
model = WhisperForConditionalGeneration.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb_config,
    device_map="auto",
    torch_dtype=torch.float16,
)

model.config.forced_decoder_ids = None
model.config.suppress_tokens = []

print("✅ Model 8-bit'da yuklandi!")
print(f"📊 Model device: {model.device}")
print(f"📊 Model dtype: {model.dtype}")

# ============================================================
# 11-QADAM: LoRA adapter qo'shish
# Faqat kichik adapter qatlamlari o'qitiladi, asosiy model muzlatilgan qoladi
# ============================================================
from peft import prepare_model_for_kbit_training, LoraConfig, get_peft_model

model = prepare_model_for_kbit_training(model)

lora_config = LoraConfig(
    r=32,
    lora_alpha=64,
    target_modules=["q_proj", "v_proj", "k_proj", "out_proj", "fc1", "fc2"],
    lora_dropout=0.05,
    bias="none",
)
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

# ============================================================
# 12-QADAM: training argumentlari (KICHIK BATCH BILAN)
# ============================================================

from transformers import Seq2SeqTrainingArguments

OUTPUT_DIR = "/content/whisper-medium-uzbek-lora"

training_args = Seq2SeqTrainingArguments(
    output_dir=OUTPUT_DIR,

    # ⭐ KICHIK BATCH SIZE (xotira tejash uchun)
    per_device_train_batch_size=1,  # 8 dan 2 ga tushirildi
    per_device_eval_batch_size=2,   # 8 dan 2 ga tushirildi
    gradient_accumulation_steps=8,  # 2 dan 4 ga oshirildi (batch size o'rnini qoplaydi)

    learning_rate=5e-5,
    warmup_steps=100,
    num_train_epochs=5,
    fp16=True,
    generation_max_length=128,
    logging_steps=25,
    eval_strategy="epoch",
    save_strategy="epoch",
    save_total_limit=2,
    report_to=["none"],
    load_best_model_at_end=True,
    metric_for_best_model="wer",
    greater_is_better=False,
    remove_unused_columns=False,
    label_names=["labels"],
    predict_with_generate=True,

    # ⭐ QO'SHIMCHA XOTIRA TEJASH
    gradient_checkpointing=True,  # ⭐ Qo'shildi
    dataloader_num_workers=0,     # ⭐ Qo'shildi
)

print("✅ Training arguments tayyor!")
print(f"📊 Batch size: {training_args.per_device_train_batch_size}")
print(f"📊 Gradient accumulation: {training_args.gradient_accumulation_steps}")
print(f"📊 Effective batch size: {training_args.per_device_train_batch_size * training_args.gradient_accumulation_steps}")

# ============================================================
# 13-QADAM: TREINING
# ============================================================

from transformers import Seq2SeqTrainer
import gc
import torch

# ⭐ Xotirani tozalash
gc.collect()
if torch.cuda.is_available():
    torch.cuda.empty_cache()
    print("✅ GPU cache tozalandi!")

# ⭐ Dataset tekshirish
print(f"📊 Train hajmi: {len(uz_data['train'])}")
print(f"📊 Test hajmi: {len(uz_data['test'])}")

if len(uz_data['train']) == 0:
    print("❌ Dataset bo'sh! 7-QADAMni qayta ishlang!")
else:
    # ⭐ Trainer
    trainer = Seq2SeqTrainer(
        args=training_args,
        model=model,
        train_dataset=uz_data["train"],
        eval_dataset=uz_data["test"],
        data_collator=data_collator,
        compute_metrics=compute_metrics,
    )

    model.config.use_cache = False

    print("\n🚀 TREINING BOSHLANMOQDA...")
    trainer.train()

    # ⭐ Modelni saqlash
    model_save_path = "./whisper-medium-uzbek-lora-second"
    trainer.save_model(model_save_path)
    processor.save_pretrained(model_save_path)
    print(f"✅ Model saqlandi: {model_save_path}")

# ⭐ Treining holatini tekshirish
import time
print("🔄 Treining davom etmoqda...")
time.sleep(5)
print("✅ Hali ishlayapti!")

# ============================================================
# 14-QADAM: LoRA adapterini saqlash
# ============================================================
FINAL_DIR = "/content/whisper-medium-uzbek-lora-second"
model.save_pretrained(FINAL_DIR)
processor.save_pretrained(FINAL_DIR)
print("Saqlandi:", FINAL_DIR)

# ============================================================
# 16-QADAM: inference uchun fine-tuned modelni qayta yuklash
# ============================================================
from peft import PeftModel
from transformers import WhisperForConditionalGeneration, WhisperProcessor

base_model = WhisperForConditionalGeneration.from_pretrained(
    MODEL_NAME, load_in_8bit=True, device_map="auto"
)
inference_model = PeftModel.from_pretrained(base_model, FINAL_DIR)
inference_processor = WhisperProcessor.from_pretrained(FINAL_DIR)
inference_model.eval()

# ============================================================
# 17-QADAM: sinov transkripsiyasi
# ============================================================
sample = uz_data["test"][0]
input_features = torch.tensor(sample["input_features"]).unsqueeze(0).to("cuda").half()

with torch.cuda.amp.autocast():
    predicted_ids = inference_model.generate(
        input_features, language="uz", task="transcribe", max_new_tokens=128
    )

transcription = inference_processor.batch_decode(predicted_ids, skip_special_tokens=True)
print("Bashorat qilingan matn:", transcription[0])

# ============================================================
# PAPKANI ZIP QILIB YUKLAB OLISH
# ============================================================

import shutil
import os

# ⭐ 1. Papkani zip qilish
model_path = "./whisper-medium-uzbek-lora-second"
zip_path = "./whisper-medium-uzbek-lora-second.zip"

if os.path.exists(model_path):
    shutil.make_archive(zip_path.replace(".zip", ""), 'zip', model_path)
    print(f"✅ ZIP yaratildi: {zip_path}")
else:
    print(f"❌ Papka topilmadi: {model_path}")

# ⭐ 2. ZIP faylni yuklab olish
from google.colab import files
files.download(zip_path)